blueprint:
  name: Scene Switch 4 Buttons (Zigbee2MQTT)
  description: >-
    Easy automation of 4 button scene switches of the kind Tuya TS0044 utilizing MQTT.
    Filter used for the MQTT topic: "zigbee2mqtt/DEVICENAME/action"
  domain: automation
  author: ibimslawa
  input:
    mqtt_device_1:
      name: MQTT device name 1
      description: "Use the device name set in Z2M."
      selector:
        text:
    mqtt_device_2:
      name: MQTT device name 2
      description: "Use the device name set in Z2M."
      default: {}
      selector:
        text:
    button_1_single:
      name: "Button 1: Single"
      description: Single press of button 1
      default: []
      selector:
        action: {}
    button_1_double:
      name: "Button 1: Double"
      description: Double press of button 1
      default: []
      selector:
        action: {}
    button_1_long:
      name: "Button 1: Long"
      description: Long press of button 1
      default: []
      selector:
        action: {}
    button_2_single:
      name: "Button 2: Single"
      description: Single press of button 2
      default: []
      selector:
        action: {}
    button_2_double:
      name: "Button 2: Double"
      description: Double press of button 2
      default: []
      selector:
        action: {}
    button_2_long:
      name: "Button 2: Long"
      description: Long press of button 2
      default: []
      selector:
        action: {}
    button_3_single:
      name: "Button 3: Single"
      description: Single press of button 3
      default: []
      selector:
        action: {}
    button_3_double:
      name: "Button 3: Double"
      description: Double press of button 3
      default: []
      selector:
        action: {}
    button_3_long:
      name: "Button 3: Long"
      description: Long Long press of button 3
      default: []
      selector:
        action: {}
    button_4_single:
      name: "Button 4: Single"
      description: Single press of button 4
      default: []
      selector:
        action: {}
    button_4_double:
      name: "Button 4: Double"
      description: Double press of button 4
      default: []
      selector:
        action: {}
    button_4_long:
      name: "Button 4: Long"
      description: Long press of button 4
      default: []
      selector:
        action: {}
mode: parallel
max: 4
max_exceeded: silent
trigger_variables:
  mqtt_device_1: !input mqtt_device_1
  mqtt_device_2: !input mqtt_device_2
trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/{{ mqtt_device_1 }}/action"
  - platform: mqtt
    topic: "zigbee2mqtt/{{ mqtt_device_2 }}/action"
action:
  - variables:
      trig_pl: "{{ trigger.payload }}"
  - choose:
      - conditions:
          - "{{ trig_pl == '1_single' }}"
        sequence: !input button_1_single
      - conditions:
          - "{{ trig_pl == '1_double' }}"
        sequence: !input button_1_double
      - conditions:
          - "{{ trig_pl == '1_hold' }}"
        sequence: !input button_1_long
      - conditions:
          - "{{ trig_pl == '2_single' }}"
        sequence: !input button_2_single
      - conditions:
          - "{{ trig_pl == '2_double' }}"
        sequence: !input button_2_double
      - conditions:
          - "{{ trig_pl == '2_hold' }}"
        sequence: !input button_2_long
      - conditions:
          - "{{ trig_pl == '3_single' }}"
        sequence: !input button_3_single
      - conditions:
          - "{{ trig_pl == '3_double' }}"
        sequence: !input button_3_double
      - conditions:
          - "{{ trig_pl == '3_hold' }}"
        sequence: !input button_3_long
      - conditions:
          - "{{ trig_pl == '4_single' }}"
        sequence: !input button_4_single
      - conditions:
          - "{{ trig_pl == '4_double' }}"
        sequence: !input button_4_double
      - conditions:
          - "{{ trig_pl == '4_hold' }}"
        sequence: !input button_4_long
