blueprint:
  name: Scene Switch 4 Buttons (Tuya) (Action Property)
  description: >-
    Easy automation of 4 button scene switches of the kind Tuya TS0044 utilizing the action property.
  domain: automation
  input:
    action_entity:
      name: Scene Switch _action entity
      description: "The _action entity of your 4-Button Scene Switch to use (for example model TS0044)"
      selector:
        entity:
          integration: mqtt
          domain: sensor
          multiple: true
    button_1_single:
      name: "Button 1: Single"
      description: Single press of button 1
      default: []
      selector:
        action: {}
    button_1_double:
      name: "Button 1: Double"
      description: Double press of button 1
      default: []
      selector:
        action: {}
    button_1_long:
      name: "Button 1: Long"
      description: Long press of button 1
      default: []
      selector:
        action: {}
    button_2_single:
      name: "Button 2: Single"
      description: Single press of button 2
      default: []
      selector:
        action: {}
    button_2_double:
      name: "Button 2: Double"
      description: Double press of button 2
      default: []
      selector:
        action: {}
    button_2_long:
      name: "Button 2: Long"
      description: Long press of button 2
      default: []
      selector:
        action: {}
    button_3_single:
      name: "Button 3: Single"
      description: Single press of button 3
      default: []
      selector:
        action: {}
    button_3_double:
      name: "Button 3: Double"
      description: Double press of button 3
      default: []
      selector:
        action: {}
    button_3_long:
      name: "Button 3: Long"
      description: Long Long press of button 3
      default: []
      selector:
        action: {}
    button_4_single:
      name: "Button 4: Single"
      description: Single press of button 4
      default: []
      selector:
        action: {}
    button_4_double:
      name: "Button 4: Double"
      description: Double press of button 4
      default: []
      selector:
        action: {}
    button_4_long:
      name: "Button 4: Long"
      description: Long press of button 4
      default: []
      selector:
        action: {}
mode: parallel
max: 4
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input action_entity
action:
  - variables:
      trig_cmd: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ trig_cmd == '1_single' }}"
        sequence: !input button_1_single
      - conditions:
          - "{{ trig_cmd == '1_double' }}"
        sequence: !input button_1_double
      - conditions:
          - "{{ trig_cmd == '1_hold' }}"
        sequence: !input button_1_long
      - conditions:
          - "{{ trig_cmd == '2_single' }}"
        sequence: !input button_2_single
      - conditions:
          - "{{ trig_cmd == '2_double' }}"
        sequence: !input button_2_double
      - conditions:
          - "{{ trig_cmd == '2_hold' }}"
        sequence: !input button_2_long
      - conditions:
          - "{{ trig_cmd == '3_single' }}"
        sequence: !input button_3_single
      - conditions:
          - "{{ trig_cmd == '3_double' }}"
        sequence: !input button_3_double
      - conditions:
          - "{{ trig_cmd == '3_hold' }}"
        sequence: !input button_3_long
      - conditions:
          - "{{ trig_cmd == '4_single' }}"
        sequence: !input button_4_single
      - conditions:
          - "{{ trig_cmd == '4_double' }}"
        sequence: !input button_4_double
      - conditions:
          - "{{ trig_cmd == '4_hold' }}"
        sequence: !input button_4_long
